# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39f1e2f65df2e803c66411669599f2f3687277fc73f590c3b83d7e2fafa29f185cf46879b345e97665819ee4c4f37f659300a08af4315d4c8856b6737ecb639d

test:
  secret_key_base: 232825da2fdba52e1fa8d5d6ed3783da0941e895a7c591d8f34e0fb9bbff09a8fdc784783dfc8f8a40f10daccb20561a6fd0239c5d0052302b5a60272dbee286

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
